server:
  port: 8080
  
spring:
  jpa:
    hibernate:      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/filipsmDb
    username: postgres
    password: root
    hikari:      connection-timeout: 20000
      maximum-pool-size: 5